CREATE TABLE IF NOT EXISTS `master_akun` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nomor_akun` varchar(20) NOT NULL,
  `nama_akun` varchar(200) NOT NULL,
  `kelompok_akun` enum('AKTIVA','PASIVA','PENDAPATAN','BEBAN') NOT NULL,
  `detail_akun` enum('KAS','PIUTANG','PERSEDIAAN','BIAYA_DIMUKA','ASET_TETAP','ASET_LAIN','KEWAJIBAN','ASET_BERSIH','LABARUGI','PENDAPATAN','PENDAPATAN_LAIN','BEBAN','BEBAN_LAIN') DEFAULT NULL,
  `level_akun` smallint(6) NOT NULL DEFAULT 1,
  `saldo_normal` enum('DEBET','KREDIT') NOT NULL,
  `level1` int(11) DEFAULT NULL,
  `level2` int(11) DEFAULT NULL,
  `level3` int(11) DEFAULT NULL,
  `level4` int(11) DEFAULT NULL,
  `namalevel1` varchar(200) DEFAULT NULL,
  `namalevel2` varchar(200) DEFAULT NULL,
  `namalevel3` varchar(200) DEFAULT NULL,
  `namalevel4` varchar(200) DEFAULT NULL,
  `id_induk` int(11) DEFAULT NULL,
  `id_user` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_nomor_akun` (`nomor_akun`),
  KEY `idx_kelompok_akun` (`kelompok_akun`),
  KEY `idx_level_akun` (`level_akun`),
  KEY `idx_id_induk` (`id_induk`),
  KEY `idx_id_user` (`id_user`),
  KEY `idx_level1` (`level1`),
  KEY `idx_level2` (`level2`),
  KEY `idx_level3` (`level3`),
  KEY `idx_level4` (`level4`),
  CONSTRAINT `fk_master_akun_induk` FOREIGN KEY (`id_induk`) REFERENCES `master_akun` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_master_akun_user` FOREIGN KEY (`id_user`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

